### ISSUE TITLE
Maximum number of LEDs 2

### ISSUE THREAD

**Issue by SummerSeaSun** [jgarff/rpi_ws281x#10]
Hi jgraff,
thanks for your work, I'm looking to a way to drive more than 5000 Led in a matrix, the software limit on a raspberry B appear to be 3200, after this I get : "addr_to_bus() read() failed".
The DMA of the pi is 4K, how this is related to the maximum number of leds?
Is there a way to increase this number?
I've looked at your code but doesn't understand what you mean for "channel", if you can use 2 PIN for PWM, you could run two python programs which point to one each other?
Thanks in advance, BR.

**Comment by Summer88** [comment]
Thanks jgraff!
