### ISSUE TITLE
Suggestion: Improve ws2811_init with distinct error codes

### ISSUE THREAD

**Issue by Gadgetoid** [jgarff/rpi_ws281x#107]
A failure in `ws2811_init` is somewhat problematic to diagnose and communicate to the user at the moment. However, I suspect that changing instances of `return -1` to return a specific error code may have repercussions in code that checks against a suspected return value of `-1`.

Would it, perhaps, be sensible to include a `ws2811_error(void)` method that returns, when called, a more specific code detailing the last error encountered by the system? A typical workflow might be:

``` c
int result = ws2811_init(ws2811);

if(result == -1){
   switch(ws2811_error()){
      case WS2811_ERR_HW_DETECT:
          printf("Failed to detect hardware");
          break;
   }
}
```

Internally this would be set just before calling `return 1` int he case of an exception.

Thoughts?

**Comment by jgarff** [comment]
Seems reasonable.  I typically like to do these as a negative result codes though.  Anything less than zero indicates a error, so the error test is simply a non-zero value.  The actual value indicates the type.  This obviates the need to call a subsequent error function.  Pull requests are always welcome.  Thanks.
