### ISSUE TITLE
Conflicting Information on mumber of LEDs

### ISSUE THREAD

**Issue by Romonaga** [jgarff/rpi_ws281x#109]
I recently closed an issue where I was asking how many LED's this library can support.  At the time I was under the impression that it was about 500.

I found this information from https://learn.adafruit.com/neopixels-on-raspberry-pi/overview
*** Note that this method of driving NeoPixels is limited by the maximum size of a kernel memory page and can in theory control up to about 450 LEDs.

However, when I went to validate this information I found that the wiki for the library says people have ran strands that had 1000's on one channel.

I have to assume that your wiki is correct and adafruit is outdated?

**Comment by jgarff** [comment]
That's correct.  Much of the information on the Adafruit write-up is out of date.  The only limit on the number of LEDs is based on your refresh rate.  More LEDs per channel, the fewer updates you can do per second.
