### ISSUE TITLE
Snake Game for 8x8 RGB LED

### ISSUE THREAD

**Issue by tayfunulu** [jgarff/rpi_ws281x#113]
Hi, 

Firstly, Thanks for this library. it's so simple to build something with it. I write a sample code with this library. Snake Game. 

If you want you could add the game on this library for another users whom have 8x8 screen like mine. 

youtube : https://youtu.be/qAIZFgBWhSc

Code : https://github.com/tayfunulu/SnakeGame/blob/master/snake.py

Best regards

Tulu

**Comment by jgarff** [comment]
That's great!  Thanks for sending the links.  I think that would be great to include as a piece of sample code.  I'll take a look.  Thanks.
