### ISSUE TITLE
Can I control RGB LED color using RPi 2?

### ISSUE THREAD

**Issue by GodShingShing** [jgarff/rpi_ws281x#114]
I want to control neopixe color using this LED(https://www.adafruit.com/products/1734) and RPi 2.
I also used a level shifter(74HC125N) following this method (http://popoklopsi.github.io/RaspberryPi-LedStrip/#!/ws2812) and changed 'strand test.py' code to control one LED color using 'strip.setPixelColor'.

from neopixel import *
# LED strip configuration:

LED_COUNT      = 1       # Number of LED pixels.
LED_PIN        = 18      # GPIO pin connected to the pixels (must support PWM!).
LED_FREQ_HZ    = 800000  # LED signal frequency in hertz (usually 800khz)
LED_DMA        = 5       # DMA channel to use for generating signal (try 5)
LED_BRIGHTNESS = 255     # Set to 0 for darkest and 255 for brightest
LED_INVERT     = False   # True to invert the signal (when using NPN transistor level shift)

if **name** == '**main**':
        strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS)
        strip.begin()
        print ('Press Ctrl-C to quit.')

```
            while True:         
            strip.setPixelColor(0, Color(0, 0, 0))
            strip.show()
```

but it didn't wok as I thought. It works turning off ( Color(0,0,0) ) but I can't express other colors. 
So I checked signal from Arduino and Rpi when I make LED turned off( Color(0,0,0) )
Arduino - https://www.youtube.com/watch?v=jLn_jijrvoQ
Rasberry Pi - https://www.youtube.com/watch?v=aosFVdK7AeM
I set time cursor for 1.2us because 1 period for 1 bit is 1.2us ( T0H = 0.4us, T0L = 0.8us)
As you can see, signal from Arduino is very stable but signal from Rpi is unstable. I use some buffers for stabilizing signal from Rpi but it didn't work.
How can I control LED colors through Rpi? 
Thanks.

**Comment by drunken-economist** [comment]
It's definitely possible, yes. Some of the discussion on this issue might help: https://github.com/jgarff/rpi_ws281x/issues/103.
