### ISSUE TITLE
WS2812b wrong sorted colors

### ISSUE THREAD

**Issue by SquallHalle** [jgarff/rpi_ws281x#122]
WS2812b:
strip.setPixelColorRGB(1,255,0,0) -> green
strip.setPixelColorRGB(1,0,255,0) -> red
strip.setPixelColorRGB(1,0,0,255) -> blue

**Comment by penfold42** [comment]
Did you set the colour order ?

**Comment by SquallHalle** [comment]
after this i rewrote order in the python file

**Comment by penfold42** [comment]
Look at strandtest_sk6812 and main.c

They both set the strip type which is how the colour order is set.

The order isn't wrong, it's just different for your strip. The ws2811 _chip_ had no fixed colour order - it was based on how you wired it up.
The ws2812 integrated the same chip die with 3 leds in a single package so has a fixed order

**Comment by Gadgetoid** [comment]
Assuming fixed and closing because this is 3 years old.
