### ISSUE TITLE
LEDs blinding randomly with strandtest

### ISSUE THREAD

**Issue by KaitoKid** [jgarff/rpi_ws281x#156]
Previous microSD broke so I reinstalled raspbian on a new one, plugged into my rpi 3 and things seem to be fine at first. Update/upgraded all my packages.

I'm powering my WS2812B 5050 LED strip with an external power source, and I have a ground running to the rpi. Double checked that I'm on pin 18 too.

Any ways I can diagnose what's wrong?

---

Testing the LED strip on an arduino shows that it works perfectly fine.

**Comment by sschroe** [comment]
Did you blacklist the audio module as mentioned in the README?

**Comment by KaitoKid** [comment]
Solved. Thanks!
