### ISSUE TITLE
Hangs on setup_pwm

### ISSUE THREAD

**Issue by InvncibiltyCloak** [jgarff/rpi_ws281x#16]
When I run ./test, it hangs at line 330 of ws2811.c - waiting for the busy signal of the PWM clock to clear after enabling the clock (at least I assume this is what is going on). I cannot find anything in the BCM2835 Peripherals about the clock for the PWM controller. I was hoping someone could point me in the direction of the documentation for this, or give me some things to try.

**Comment by InvncibiltyCloak** [comment]
So, as far as I have tested, this is not the issue. From a fresh reboot, no sounds played, it still does the same thing. I tried blacklisting all sound-related kernel modules, but they are included in initramfs and get loaded anyway. I didnt really want to rebuild it without sound, since its a little above my linux skill.

I am working on making a program to mess around with and watch the registers. I'll let you know if I find anything.

**Comment by InvncibiltyCloak** [comment]
I have no clue what changed but it seems to be working when I tried it again today. Both before and after were fresh Raspbian installs, so not much could have changed. Anyway, thanks for the great library.

**Comment by OliverHoermann** [comment]
Hi, I experienced the same issue on the RPi 2 B (the quad core one), whereas the same SD-card worked seamlessly on my RPi B. I already tried to extend the usleeps within the setup_pwm code, but to no avail. 
That said, thanks for providing the library!

**Comment by jgarff** [comment]
Thanks for the additional information.  Unfortunately, I don't have a RPi 2 to try to reproduce the problem with.  It's certainly possible that the peripherals behave differently between revs of the processor.    InvisibilityCloak, is it possible that overclock settings may have been changed between your various attempts at getting this working?  Thanks.

**Comment by InvncibiltyCloak** [comment]
As far as I remember that is not the case. Both were fresh installs of Rasbian, so stock overclock settings should have been in effect.

**Comment by OliverHoermann** [comment]
Jeremy,
I noticed you used peripheral base 0x20000000 in your routines. With the RPi 2 the bae has changed due to the larger memory. The new peripheral_base is now 0x3f000000.

I guess that's the core problem.

**Comment by jgarff** [comment]
Thanks.  I was afraid there would be these types of differences between
chip revs.

**Comment by growlf** [comment]
So, what do I do to resolve this on my RPi2?

**Comment by laboratories** [comment]
@growlf 
look at
https://github.com/jgarff/rpi_ws281x/issues/25
