### ISSUE TITLE
Add support for GRB and BGR strips

### ISSUE THREAD

**Issue by CrazyCoder** [jgarff/rpi_ws281x#17]
Original Adafruit library [allows to specify the strip type](https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp#L46) (RGB, GRB, BGR).

It would be nice if this package supported it as well.

Right now you have to modify the order of colors in neopixel.py, like this for GRB:
```python
return (green << 16) | (red << 8) | blue
```

This has to be duplicated in the `setBrightness` method.

**Comment by jgarff** [comment]
Good idea.  I'll put that on the ToDo list.

**Comment by madsi1m** [comment]
or use setPixelColorRGB and swap values?
