### ISSUE TITLE
Brightness with setBrightness: 0 brightest and 255 darkest

### ISSUE THREAD

**Issue by Thor77** [jgarff/rpi_ws281x#21]
If i set the brightness with the setBrightness-function from neopixel.py to 0, the leds are very bright and if i set it to 255, they are very dark. Is this a problem with my LED-Stripe (ws2812b) or did anyone else noticed this too and the doc-string should be modified?

**Comment by jgarff** [comment]
I haven't seen this the problem.  Is this still a issue for you?

**Comment by Thor77** [comment]
Yes: https://github.com/jgarff/rpi_ws281x/pull/22#issuecomment-71337701

**Comment by jgarff** [comment]
Unfortunately, I'm still not able to reproduce your issue.  I just tested by adjusting the brightness value in strandtest.py.  At 255 I get full brightness, at 0, it appears off.  Can you please try to replicate using this method?  Thanks.

**Comment by jgarff** [comment]
I suspect that your tree is out of date.  There were changes recently which changed the way the brightness works.  Please see:

https://github.com/jgarff/rpi_ws281x/commit/de5a765a57e6c220ae70b570d6631b84163ac841

Prior to this changeset, when using python, there is a side effect of the way that brightness was handled previously.  Please see Tony's comment in:

https://github.com/jgarff/rpi_ws281x/pull/22#issuecomment-71334376

This should no longer be a issue in the latest codebase.

**Comment by Thor77** [comment]
Sorry for my late answer, but i can confirm the issue is solved in the latest codebase, thanks :)
