### ISSUE TITLE
Error in Strandtest.py

### ISSUE THREAD

**Issue by JeanjacketSmackit** [jgarff/rpi_ws281x#211]
When running strandtest.py for the first time after cloning the git repository today I encounter this error:
undefined symbol: clock_gettime

This is on Raspbian. Does anyone know what I need to do to fix this?

**Comment by samhollenbach** [comment]
How did you fix this??

**Comment by jgarff** [comment]
Please pull and try with the latest master branch.  I ran into this as well yesterday when updating my raspbian distro, and have just pushed the fix.  Thanks.

**Comment by samhollenbach** [comment]
Works perfect, thanks!
