### ISSUE TITLE
Wrong control of 200 RGB WS2811 led string

### ISSUE THREAD

**Issue by Max22b** [jgarff/rpi_ws281x#226]
Hi to everyone, I apologize for my English. I have a raspberry 2 with four strings ws2811 5V connected in series for a total of 200 led. I downloaded the library and modified the parameters of the file strandest.py . The power supply is brought to the first and third string. I connect the string at GPIO18 PWM via SN 74AHCT125 and i put a capacitor before power supply.
I cannot control the last 50 LEDs that always appear red weak. Can it be a frequency or power problem?
Thanks to everyone!!!
Massimiliano from Italy :-)

**Comment by penfold42** [comment]
You probably are seeing voltage drop along the strip.

I needed to supply power at both ends of my 144 led strip

**Comment by Max22b** [comment]
OK thanks. I thought of that problem and I put power supply at the third string but I did not solve it. now I try to feed it in the end and see if I fix it. 
Is it possible a signal data problem? poor data voltage? Thanks a lot

**Comment by penfold42** [comment]
If you're wiring is good then the data signal will be fine. Each led regenerates the data signal.

I just reread your original post - does the last strip change and display data but with blue and green missing ?
Or is it a static dim red ?

**Comment by Max22b** [comment]
no no, the last 50 led don't display the data...but a pooooor  red light,,,  
I also changed string but gets the same problem. thanks

**Comment by Max22b** [comment]
Resolved. it was a power supply problem and string with bug. thank you!!!!
