### ISSUE TITLE
Huge voltage drop and RGBW issue

### ISSUE THREAD

**Issue by resetscoder** [jgarff/rpi_ws281x#230]
Hi ! I've just bought an Sk6812 rgbw  in order to build a sunrise alarm clock with a Raspberry Pi B. The led strip is 5m with 60led/m, so that I have a 20A/5V power supply (60mA per led). But I'm facing with some issues while using the white led ! More than half of the strip suffer from a Red shift and intensity of white is lowering to zero when I try to go from color(0,0,0,0) to color (255,255,255,255). Even if I plug the power from the two side of the strip it suffer the same in the center.

My wiring is done with breadboard, May it have an impact on the drop of voltage ?

Is someone facing the same issue ?
It seems to work better with SK6812_lowlevel.py (no lowering of Rgb (without white)), so I wonder if it may come from the rpi _ws281x ?

**Comment by penfold42** [comment]
Breadboard wire is terrible for power connections.

Both the power and ground wires need to be good size cables.
Mains wiring has to carry 10+ amps - look how much thicker the conductors are.

**Comment by resetscoder** [comment]
Thanks for the tips ! I will make the setup with some good wires !
