### ISSUE TITLE
Combinations of PWM, PCM, and SPI?

### ISSUE THREAD

**Issue by grantHarris** [jgarff/rpi_ws281x#232]
Is it possible to simultaneously output to the PWM, PCM, and SPI channels or can only one output method be used at once?

**Comment by jgarff** [comment]
Unfortunately, no.  The underlying hardware is shared (DMA, PWM, PCM, etc.).

**Comment by d21d3q** [comment]
Is  `strip.show()` blocking function? If yes, then one could have several different strips on two PWM pins, and one on PCM, and share one DMA - only one strip will use it at time?
