### ISSUE TITLE
no level shifter is needed

### ISSUE THREAD

**Issue by impynutz** [jgarff/rpi_ws281x#24]
if you have a look at the datasheet you will see that it just needs 0.7V as high level. I can directly drive the leds at 3.3V logic level.

**Comment by jgarff** [comment]
I think you are misreading the spec.  The input high voltage is listed as
0.7 * Vdd.  This is extremely common for logic devices.  When Vdd is at 5V,
the minimum high level is then 3.5V.  It may indeed work at 3.3 but will
violate the spec and isn't guaranteed.

http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Components/LED/WS2812.pdf
