### ISSUE TITLE
Raspberry Pi A+ not supported - new hardware revision

### ISSUE THREAD

**Issue by datagod** [jgarff/rpi_ws281x#241]
I have a batch of Raspberry Pi A+ models that are not supported by rpi_ws281x.

Here is the error that is raised:
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

Here is the revision information on the A+:

Hardware: BCM2835
Revision: 900021

This revision number follows the new style revision codes that are in use since the release of the Pi2 series.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by jgarff** [comment]
Please retry with the latest.  Should be fixed in commit: 7f08d491f0ae22c20a63394df6a5c8ebe80c0be4

**Comment by datagod** [comment]
Excellent.  Many thanks.
