### ISSUE TITLE
Library won't run without the hdmi display plugged in

### ISSUE THREAD

**Issue by marbaque** [jgarff/rpi_ws281x#242]
i am running a 90 led strip, a buttons interface and sound. I used a USB audio interface to solve the PWM issue between the pin 18 and the sound card. So far, it is fine. 

However, if I start the Rpi3 without plugging the hdmi display, the neopixels won't run. Is there any known workaround for this? I really need to be able to start the pi3 without plugging a display.

**Comment by penfold42** [comment]
Yes, you need to disable onboard audio
