### ISSUE TITLE
Ws2812 LEDs do only show 1 Color

### ISSUE THREAD

**Issue by SillyScientists** [jgarff/rpi_ws281x#244]
After I have installed the libary and started to run the strandtest.py. I just got that issue that everything that is played is in red. So there is no other color than the red ones.
I hope you can help me.
Thanks in advance

Dominik Schumann

**Comment by SillyScientists** [comment]
Now flickers every LED that isn't on.

**Comment by sschroe** [comment]
Please provide more information on the hardware setup and the solutions you already tried from the README (audio blacklisting, ...)

**Comment by SillyScientists** [comment]
Using Rpi 2B 
With 240 LEDs of WS2812B Used the strandtest.py with editing the LED Count at First.
Changed after then the Frequency to 400kHz.
Nothing changed.
Edited the Channel as Well changed nothing

Before I Used the libary I blacklisted the audio and as the HDMI thingy isn't for the Rpi 2B, I Just ignored it.

Should I use the SPI Channel ? 
Which PIN should I use and should I Change any settings ? 

Thanksgiving in advance

**Comment by SillyScientists** [comment]
So I just used the SPI PIN and the structures etc. works fine, but the color will constantly be on red.

**Comment by sschroe** [comment]
What about the used voltages and a level shifter?

**Comment by SillyScientists** [comment]
I use 5 V ans 10 A 
A Level shifter ? 
I don't have anyone

**Comment by sschroe** [comment]
In that case grab something like an 74HCT125 and add it.

**Comment by SteMMo33** [comment]
I compiled the library and the test app for Tinker, forcing SPI port.
The application is running but the signal is regular at first (let's say 8 LEDs) then the signal is larger and irregular.
Of course the LEDs are blinking...

**Comment by Gadgetoid** [comment]
Closing since this is stale and I like the number of issues to go down sometimes :laughing: instead of just up :sob: 

Feel free to open a new issue the Python bindings if it's still relevant- https://github.com/rpi-ws281x/rpi-ws281x-python
