### ISSUE TITLE
Library is setting leds by three

### ISSUE THREAD

**Issue by b-stud** [jgarff/rpi_ws281x#249]
Hello!  I'm facing a weird issue with the file SK6812_lowlevel.py and my WS2811

Actually, leds are set by three, which means that if I execute this code : 

`strip1.setPixelColor(0, color1)`

Then LED 0, LED 1 and LED 2 will all be set to color1 while I would expect only the 0 to be set.

Would anyone ever faced the sime thing?

**Comment by korbav** [comment]
Please close this issue, it was the strip which was designed this way, no relation with the library.
Thanks and sorry for the inconvenience.
