### ISSUE TITLE
Running without root/sudo

### ISSUE THREAD

**Issue by ffleandro** [jgarff/rpi_ws281x#260]
Is it possible to run the `./test` without sudo?

I've seen several issues mentioning this problem, but none addressing it directly.
I can successfully run the C code *WITH* sudo.
But in my application I need to use Python and can't run it with sudo.

What exactly is the limitation that makes `sudo` mandatory and is there any workaround without raising any security issues?

In this forum [thread](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=22515#p216411) there is an explanation on why changing permissions of `/dev/mem` won't work, but I'm a bit out of my league here.

Any help?

**Comment by ffleandro** [comment]
This issue is being addressed in #251

**Comment by ffleandro** [comment]
I have successfully used this library through SPI by changing the access in `mailbox.c` from `/dev/mem` to `/dev/gpiomem`.

### *WARNING:* This will make the PWM communication method unusable!

**Comment by PandorasFox** [comment]
I fixed that in #257, which'll be merged shortly.

**Comment by Gadgetoid** [comment]
I think this is fixed? Closing, but happy to re-open if any further issues arise.
