### ISSUE TITLE
Rust Support

### ISSUE THREAD

**Issue by JMurph2015** [jgarff/rpi_ws281x#265]
Hi people,
I have a Rust wrapper in the works that uses bindgen to interface the C code with Rust.  It works pretty well, but I wouldn't mind some help abstracting the FFI away ( needs hand-written Rust code to go from auto-generated functions to a nice API )  Anyway, I was just wondering if anyone was interested in integrating this with the main repo.  The crate name "rpi_ws281x" is still available as well as "ws2811" if that's preferred ( I took rs_281x for the interim ).
[https://github.com/JMurph2015/rs_ws281x](https://github.com/JMurph2015/rs_ws281x)
Thanks!
Joseph Murphy

**Comment by Gadgetoid** [comment]
(the following is more for posterity than directed at you @JMurph2015)

As discussed in #267 we're now collecting language ports of rpi_ws281x under the GitHub org at https://github.com/rpi-ws281x

This is to prevent maintenance burden in this repository.
