### ISSUE TITLE
odroid xu4 compatibility

### ISSUE THREAD

**Issue by artifishional** [jgarff/rpi_ws281x#268]
odroid xu4 as well as rasberry pi supports GPIO / spi interfaces. Is it possible to use this code for this platform?

**Comment by Gadgetoid** [comment]
Unfortunately not. See the Wiki: https://github.com/jgarff/rpi_ws281x/wiki

This library uses features specific to the Broadcom SOC on the Raspberry Pi, and supporting other boards is outside its scope.
