### ISSUE TITLE
How can I install this package directly through pip?

### ISSUE THREAD

**Issue by KevinNovak** [jgarff/rpi_ws281x#288]
I've tried running
`sudo pip install git+https://github.com/jgarff/rpi_ws281x.git#"egg=rpi-ws281x&subdirectory=python"`
and this seems to get most of the way but fails:

> creating build/temp.linux-armv7l-3.6
> 
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.6m -c rpi_ws281x_wrap.c -o build/temp.linux-armv7l-3.6/rpi_ws281x_wrap.o
> 
> gcc -pthread -shared build/temp.linux-armv7l-3.6/rpi_ws281x_wrap.o -L../. -lws2811 -lrt -o build/lib.linux-armv7l-3.6/_rpi_ws281x.cpython-36m-arm-linux-gnueabihf.so
> 
> **/usr/bin/ld: cannot find -lws2811**
> 
> collect2: error: ld returned 1 exit status
> 
> error: command 'gcc' failed with exit status 1

The end goal is to be able to include this in a **requirements.txt** file.

**Comment by KevinNovak** [comment]
Manually attempting to build returns the same failure... and manually building with scons works. Perhaps the something called from setup.py needs to be modified?

**Comment by Gadgetoid** [comment]
`sudo pip install rpi_ws281x`

I'm planning for this to replace the Python libraries available in this repository.

I am currently working on an update (due imminently) to bring it back to full compatibility with the examples available here. (Plus include a wheel for Python 3.5 armhf)

**Comment by KevinNovak** [comment]
Awesome! I had no idea there was a published package. Thanks!

**Comment by edorgeville** [comment]
@Gadgetoid This should be on top of the README! 🙏
