### ISSUE TITLE
SCons doesn't work on RPi 

### ISSUE THREAD

**Issue by ismailuddin** [jgarff/rpi_ws281x#29]
This looks like a really cool library, but unfortunately I cannot get it to work on my RPi. I've installed all the necessary dependencies it would require as written in your README file and on the Adafruit website. But when I run scons inside the directory, I just get 'Illegal instruction'. Even tried reinstalled Raspbian on a new SD card, but still same issue... Any ideas?

**Comment by ismailuddin** [comment]
After spending the good part of today trying to get this to work, I found the issue is related to using the git command on the RPi itself. For some reason, the files downloaded using git appear corrupted. I cloned this repository using the Git desktop app on Windows, and transferred the files over SFTP to the RPi, and scons worked perfectly fine. Library works brilliantly! The whole git issue though is quite weird...

**Comment by laboratories** [comment]
try just downloading the zip of the archive.. that worked fine for me
