### ISSUE TITLE
RuntimeError: ws2811_init failed with code -5 (mmap() failed)

### ISSUE THREAD

**Issue by melzoghbi** [jgarff/rpi_ws281x#296]
Hi,

I am getting this error after i installed neopixel on my RPI3 model B. This was working before i did:
apt-get upgrade 

But after i re-installed my conda environment with all required packages including rpi_ws281x i am still getting this detailed error:

Can't open /dev/mem: Permission denied
Traceback (most recent call last):
  File "listen.py", line 260, in <module>
    strip.begin()
  File "/home/pi/miniconda3/envs/myapp/lib/python3.4/site-packages/rpi_ws281x/rpi_ws281x.py", line 124, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
**RuntimeError: ws2811_init failed with code -5 (mmap() failed)**

![image](https://user-images.githubusercontent.com/11993393/41175038-d2815d0c-6b29-11e8-9c25-058203e88abb.png)

Here is my current version of Raspbian stretch:

Linux rpi_moelzogh 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

Also, when i try to run ./test it nevers come up with output as mentioned in the GitHub installation instructions.

![image](https://user-images.githubusercontent.com/11993393/41175113-1175cdfe-6b2a-11e8-9bec-b37daaf51b62.png)

Any advice?

Thanks.

**Comment by nvl1109** [comment]
I'm using RPi Zero W, and got same issue.
About 1month ago, I install this and make WS2812B led strip works fine.
From that time, I don't upgrade the system.

I'm using PWM mode.

**Comment by melzoghbi** [comment]
@nvl1109 i do have root permission and i am having this issue.

**Comment by Gadgetoid** [comment]
What happens if you run `sudo python strandtest.py`?
