### ISSUE TITLE
Installation problem on RPi 3

### ISSUE THREAD

**Issue by Simonv92** [jgarff/rpi_ws281x#307]
Hi,
I'm trying to install Neopixel library on my rpi 3 running octopi. I'm having problems when I run sudo python setup.py install as I show you in the photo. I've tryed on two sd card (one of them with fresh install) with same results... 
thank you very much!!

![adafruit](https://user-images.githubusercontent.com/11270330/43482438-fbba1566-9508-11e8-8013-48f24741e64f.jpg)

**Comment by etanx** [comment]
This looks like the 'bad zip file' error from thread #290.
Try out hnoesekabel's solution of deleting the old zip file and getting a new one.  Work for you?

**Comment by Simonv92** [comment]
Hi,

I've tryed with "sudo pip install rpi_ws281x"and it works 😃thank you!!

________________________________
Da: etanx <notifications@github.com>
Inviato: mercoledì 1 agosto 2018 20:38
A: jgarff/rpi_ws281x
Cc: Simonv92; Author
Oggetto: Re: [jgarff/rpi_ws281x] Installation problem on RPi 3 (#307)


This looks like the 'bad zip file' error from thread #290<https://github.com/jgarff/rpi_ws281x/issues/290>.
Try out hnoesekabel's solution of deleting the old zip file and getting a new one. Work for you?
