### ISSUE TITLE
Anyone interested in some dedicated hardware?

### ISSUE THREAD

**Issue by JMurph2015** [jgarff/rpi_ws281x#308]
I'm considering making a small-run of custom Pi Hats for the Raspberry Pi Zero that would simplify the hardware connections down to a 5V power in that powers both the Pi and the lights, and four screw terminals for the strip connections.  Anyone interested in this direction (from helping on PCB design to ordering together to increase quantity to outright producing the boards for sale, since we have some commercial guys here too)?

Features:
* high current traces from 5VIN and GND to LED5V and LEDGND
* voltage stabilization on the circuit powering the Pi Zero
* built-in step-up from 3.3V logic level to 5V on the LED signal lines

This should only take a few parts and a couple terminals, but I think it would really help drive the ecosystem forward (especially if someone like Adafruit picked it up and put it into mass production).

Edit: added tentative design

**Comment by davthomaspilot** [comment]
I already did something similar, except in my case, I use 12V led strings and have a Pololu step-down regulator for five volts from the 12V bulk power.

Works fine for my purpose.  Cost isn't a big deal--$5 for 10 cards from SEEED, so no need to pool orders.

**Comment by Gadgetoid** [comment]
Closing, since this is just a feeeeww years old.
