### ISSUE TITLE
Unable to run from parent folder

### ISSUE THREAD

**Issue by john-santose** [jgarff/rpi_ws281x#309]
I have installed the library per instructions and the LED's work properly when I run the file straight from the examples folder. However when I try to import the strandtest example into a project in the parent folder i get the error of -   ImportError: No module named 'neopixel'.      I have tried the "./setup.py install" that is recommended for calling neopixel from anywhere but it still throws a code. Any suggestions would be most appreciated.

**Comment by Gadgetoid** [comment]
Do not use the Python library from this repository- see: https://github.com/rpi-ws281x/rpi-ws281x-python
