### ISSUE TITLE
Interference with wiringPi

### ISSUE THREAD

**Issue by stepugnetti** [jgarff/rpi_ws281x#31]
I'm experiencing an unexpected behavior of wiringPi softPwm when used together with rpi_ws281x. I'm not using the hardware Pwm via wiringPi. Is this just due to misconfiguration of wiringPi or such interferences are to be expected?

**Comment by jgarff** [comment]
I suspect the soft PWM still uses the pwm module for timing, but with more software to control additional gpios.  If the PWM is in use it will conflict with the leds which is probably what you are seeing.

**Comment by stepugnetti** [comment]
Thanks!
