### ISSUE TITLE
ws2811_render locking up

### ISSUE THREAD

**Issue by grantHarris** [jgarff/rpi_ws281x#315]
This is C++, not being used with Python.

I'm having an issue where my code freezes as soon as I hit the ws2811_render function. I've put log statements before and after the call to confirm this. I'm using the compiled .a file in a project and I had it working before but had to rebuild my Sd card. I'm using the latest raspbian (June 2018). 

The init step (ws2811_init) seems to execute fine and I tried it with a version of the code that was known to work in the past and have the same issue.

Has anyone seen this before?

**Comment by grantHarris** [comment]
This is on a Raspberry pi 3 Model B v 1.2

**Comment by samuelbles07** [comment]
Hi, this thread already closed. Did you got the solution?
