### ISSUE TITLE
Possibility to run different strip types from the same data pin

### ISSUE THREAD

**Issue by timkoers** [jgarff/rpi_ws281x#318]
I've bought a few WS2812B led strips, of which I thought they where all the same.
But time has proven me wrong, one of them is GRB the other one GBR etc.

Since I'd like to chain them all together, is there any possibility to drive all of those different leds with a single data line? So for example provide that the first strip has got the leds ranging from 0 to 30 and are of the type RGB, the second strip has leds ranging from 31 to 68 and are of the type GRB and the third strips has leds ranging from 69 to 100 and are of the type GBR.

Is that possible or do I need to make somekind of converter?

**Comment by Gadgetoid** [comment]
I suspect it would probably just work if you made note of the types/positions of your pixels and swapped the colour order accordingly depending on index.

For example you would send all data into your function as RGB, but if the pixel index is `>=31` then you would just swap the colour order with: `r, g, b = g, r, b` and clock out as normal.

I don't see why that wouldn't work- although I would chain them together and try driving them all without any colour conversion first to verify they'll work at all.
