### ISSUE TITLE
'module' object has no attributes 'WS2811_STRIP_RGB'

### ISSUE THREAD

**Issue by skomatin** [jgarff/rpi_ws281x#322]
I followed the instructions exactly as stated in the README and installed the python wrapper as instructed. However I get the error 'module' object has no attributes 'WS2811_STRIP_RGB' which I am only getting when I run the program on the Ubuntu Mate and not when I am running on Raspbian. 

On an additional note, the test without the python wrapper works fine. 
Could you let me know what the fix could be?

**Comment by sanyatuning** [comment]
I got this error when I installed swig 3.0
After I switch to swig 2.0 this error goes away

**Comment by Gadgetoid** [comment]
There should generally be no need to compile at all, since you can just `sudo pip install rpi_ws281x`. Have you run into this issue with the Python bindings?
