### ISSUE TITLE
neopixel.py code not running correctly

### ISSUE THREAD

**Issue by Hotke1** [jgarff/rpi_ws281x#328]
I have a RP1 3b.  I am trying to get it to run this software in order to run my neopixel strands.  Ever time it tries to call up line 9 in the neopixel.py program it gives me a error that it can not find the rpi_ws281x file.  Is there a simple way to fix this issue?

pi@Hotke1:~/rpi_ws281x/python $ sudo python strandtest.py
Traceback (most recent call last):
  File "strandtest.py", line 9, in <module>
    from neopixel import *
  File "/home/pi/rpi_ws281x/python/neopixel.py", line 5, in <module>
    import _rpi_ws281x as ws
ImportError: No module named _rpi_ws281x

**Comment by bastianum** [comment]
Same here

**Comment by Luro02** [comment]
`sudo pip install rpi_ws281x
`
or
`sudo pip3 install rpi_ws281x
`
?

**Comment by Gadgetoid** [comment]
You should not be using `from neopixel import *` in any code intending to use the RPi ws281x Python bindings. Rather, use `from rpi_ws281x import *`.

Seee - https://github.com/rpi-ws281x/rpi-ws281x-python/issues/10
