### ISSUE TITLE
Yet another ImportError: No module named rpi_ws281x

### ISSUE THREAD

**Issue by Psychokiller1888** [jgarff/rpi_ws281x#341]
I have multiple pi zero running the same. They all have a neopixel ring. 2 of them are working great, the third one fails with that import error.

I have deleted the git cloned directory, sudo scons'ed a fresh pull, `sudo python setup.py build` and `sudo python setup.py install`, it always fails for that same import error.... I just don't get it

**Comment by LongLane** [comment]
Could be a corrupt SD Card. Reformat and start anew... Has happened to me a few times.
