### ISSUE TITLE
Support for rasPi2 

### ISSUE THREAD

**Issue by iMattmax** [jgarff/rpi_ws281x#36]
Can I use this with the rasPi2 also or is the rasPi2 not supported yet?

**Comment by usefulthink** [comment]
There is a fork of this repo that works really well on the rpi2: https://github.com/richardghirst/rpi_ws281x

**Comment by KuenzelIT** [comment]
I can confirm that this one does not work as is on my RPI2, but the fork posted by usefulthink works with an unmapping problem when terminating.

**Comment by jgarff** [comment]
I just created a rpi2 branch which supports newer kernels and the Raspberry Pi 2.  This is a testing branch, so please give it a shot and let me know if you run into problems.  Thanks

**Comment by Vikaton** [comment]
@jgarff is the rpi2 branch in master now or is it still seperate? I have an rPi2 I'd like to use this library with and I'm wondering which branch I should use.

**Comment by jgarff** [comment]
Please use the main branch.  I merged the rpi2 branch into the master a few
weeks ago.

**Comment by Vikaton** [comment]
Thanks for the heads up! I'm writing bindings for your library in Rust (https://github.com/Vikaton/ws2811-rs) , would you mind a PR to add a seperate folder for the Rust (like golang) when I'm finished?

**Comment by jgarff** [comment]
Sure.  Send me a pull request when you're ready and I'll take a look.
