### ISSUE TITLE
Hangs on strandtest.py

### ISSUE THREAD

**Issue by bbbenji** [jgarff/rpi_ws281x#40]
I am running rpi_ws281x on RPi B ArchArm with a NeoPixel Ring 24. After starting strandtest.py nothing happens. I am unable to terminate and no output is visible. How can I start to diagnose this? 

EDIT:
Here is the output of `sudo python -m trace --trace strandtest.py`
https://gist.github.com/bbbenji/44ed02ea6c8e47a6f8c5

**Comment by KuenzelIT** [comment]
I got the same problem. It works with this fork, while producing a unmap error at the end:
https://github.com/richardghirst/rpi_ws281x

**Comment by antti004** [comment]
Same thing. Hangs at strip.begin()
Using RPI2.

**Comment by electrodynatronic** [comment]
Another here with the same problem. This lib works fine with the single core rPi, but does not work with rPi 2.

**Comment by usefulthink** [comment]
@antti004 @electrodynatronic Are you using the new [rpi2-branch](https://github.com/jgarff/rpi_ws281x/tree/rpi2)? The version in master doesn't support the rpi2.

**Comment by electrodynatronic** [comment]
@usefulthink Nay sir, I had failed to notice that! TYVM.

**Comment by m4rkireland** [comment]
@electrodynatronic is it working for you now? I am using the rpi2-branch and still having issues. ./test runs fine.

**Comment by jgarff** [comment]
I've now merged the rpi2 branch into the master.  Please re-test and re-open if necessary.  Thanks.
