### ISSUE TITLE
Parsing RGB values to a python script #question

### ISSUE THREAD

**Issue by TieHaxJan** [jgarff/rpi_ws281x#413]
I wondered if there is the possibility to parse rgb values to a python script, to dynamically change the color of f.e. an color wipe animation. Thanks!

**Comment by Romonaga** [comment]
Python has some great utilities for this. https://docs.python.org/3/library/colorsys.html, I see no reason why you cant do this.  I do it from c++ and php, nodejs......

**Comment by Gadgetoid** [comment]
Full Python library & examples are here - https://github.com/rpi-ws281x/rpi-ws281x-python
