### ISSUE TITLE
doesn't work on jetson NANO, please help !!

### ISSUE THREAD

**Issue by elpimous** [jgarff/rpi_ws281x#416]
Hello,
i tested and had success with neopixels on RPI4, on your libs !!
But i changed board for a Jetson NANO, and i can't use your libs anymore !
here is the error : 

```
from rpi_ws281x import Adafruit_NeoPixel, Color
pixels = Adafruit_NeoPixel(16, 12)
pixels.begin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rpi_ws281x/rpi_ws281x.py", line 131, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
```

Could you please help me add light to my robot pet ? Thanks a lot
Vincent

**Comment by Gadgetoid** [comment]
The library is titled "rpi" ws281x for a reason. It does not, and will not ever support the Jetson NANO or any other platform than the Raspberry Pi. The techniques used to drive WS281x pixels are complicated and the resulting code is very highly specific to the BCM28XX. See: https://github.com/jgarff/rpi_ws281x/issues/338
