### ISSUE TITLE
Once again: Yet another ImportError: No module named rpi_ws281x

### ISSUE THREAD

**Issue by masoudl** [jgarff/rpi_ws281x#425]
Hi, 
I had set up my RP according to the instructions in [tutorials-raspberrypi.com](https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/), and the set up worked fine at first.
But after some changes, and adding modules needed to support touch sensors, I started getting the "No module named rpi_ws281x".
Seeing the comments on issue No module named #341, I figured my SD card may become corrupted. So I reformatted and installed the OS, and followed  [tutorials-raspberrypi.com](https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/) again.
Note: This time I have not added any other modules. 

I am still getting this error. Any thoughts?

**Comment by Gadgetoid** [comment]
You're following a tutorial that's at least 3 years out of date. `rpi_ws281x` is not provided by Adafruit's NeoPixel library. You should probably dig up a better guide, eg: https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage

**Comment by masoudl** [comment]
Thank you,
