### ISSUE TITLE
Dart binding for rpi_ws281x

### ISSUE THREAD

**Issue by darmar-lt** [jgarff/rpi_ws281x#426]
Recently I developed Dart binding for rpi_ws281x:
  https://github.com/darmar-lt/rpi-ws281x-dart

I hope, somebody will find it useful.

**Comment by Gadgetoid** [comment]
Feel free to raise a PR to add this to the list in the README. We also have a GitHub Org for collecting rpi_ws2812 bindings if you're interested - https://github.com/rpi-ws281x/

**Comment by darmar-lt** [comment]
Hello Gadgetoid,
I think, it would be nice to have rpi-ws281x-dart as one of the bindings on https://github.com/rpi-ws281x/ 
Can you add it there?

**Comment by Gadgetoid** [comment]
I believe that's something @penfold42 has to facilitate. For some reason I thought I'd set up that org, but apparently not!

**Comment by darmar-lt** [comment]
Thank you Gadgetoid. Unfortunately @penfold42 doesn't write his email. Therefore I have no way to contact him/her.

**Comment by penfold42** [comment]
Done - I think !

**Comment by darmar-lt** [comment]
@penfold42: Thank you!

**Comment by Gadgetoid** [comment]
> him/her

Singular "them" for unknown third person :smiley: 

I think this is resolved, now. Glad to have you aboard!
