### ISSUE TITLE
Raspberry Pi 4B 4GB v1.4 cannot use this library

### ISSUE THREAD

**Issue by ZhiJGuo** [jgarff/rpi_ws281x#436]
It is recommended to modify rpihw.c to support Raspberry Pi 4B 4GB v1.4
![image](https://user-images.githubusercontent.com/49022851/103194692-6b6a3800-491b-11eb-89f6-9c7b6fe160b0.png)

**Comment by Gadgetoid** [comment]
Closing since this was fixed in https://github.com/jgarff/rpi_ws281x/commit/0cc85fd9b7838c7badd10d29d3598d3da69e486e
