### ISSUE TITLE
Selection code with extra functions (though rough)

### ISSUE THREAD

**Issue by gordonfreeman04** [jgarff/rpi_ws281x#450]
Hi! I have adapted the python version of your strandtest so that the user can select the function they want to use, and added a random pixel color, user color, and color gradient options. Would you have any interest in this code for your repository?
[light.py.txt](https://github.com/jgarff/rpi_ws281x/files/6135396/light.py.txt)

**Comment by Gadgetoid** [comment]
If you're interested in contributing Python examples you should raise them as a pull request against: https://github.com/rpi-ws281x/rpi-ws281x-python
