### ISSUE TITLE
failed with code -3 (Hardware revision is not supported) with Nanopi neo core

### ISSUE THREAD

**Issue by juanCGVE** [jgarff/rpi_ws281x#470]
Hello I try to use the library https://github.com/pimoroni/unicorn-hat but when I try tu run the code example I get a error of the subject.

If I execute cat /proc/cpuinfo | grep Revision 

Show the next information:
Revision        : 0000

Does anyone have any idea how to fix it?
Thank you very much in advance

**Comment by Gadgetoid** [comment]
*taps the sign*

https://github.com/jgarff/rpi_ws281x/issues/338
