### ISSUE TITLE
Limit of 339 LED when using SPI on RPI4B.

### ISSUE THREAD

**Issue by Old-Engineer** [jgarff/rpi_ws281x#473]
Hi,
While using SPI to drive single string of LEDs I have found a limit of 339 LEDs. Any more results in an error.
I need to drive 900.
Anyone know how to overcome the limit?

thanks

**Comment by Gadgetoid** [comment]
Possibly the SPI buffsize. See: https://github.com/jgarff/rpi_ws281x#spi

**Comment by Old-Engineer** [comment]
Thanks for the reply. I had already found this detail and entered it into the correct file. After receiving your comment I rechecked the change and found I put a comma in where a space should go between entries. That resulted in the buffer size still being too small. Once corrected it worked a treat. I can  now control my string of 900 LEDs.
Thanks again.

**Comment by Gadgetoid** [comment]
I've been there, no worries!
