### ISSUE TITLE
"test" program can not run on Pi 3B but can run on Pi 4B

### ISSUE THREAD

**Issue by dfybc** [jgarff/rpi_ws281x#476]
I build the 'test' program on raspiOS version "buster 2020-12-02", 
The test program can light ledstrip on Pi 4B, but can not light ledstrip on Pi 3B.

**Comment by Gadgetoid** [comment]
I suspect this is because audio must be disabled on 3B, since its use conflicts with the PWM setup that rpi_ws281x uses by default. See the README for a full list of caveats.
