### ISSUE TITLE
Can't use it in C++

### ISSUE THREAD

**Issue by Kkikeur** [jgarff/rpi_ws281x#500]
**Dear jgarff we tried every option possible , but its end to issue or error that we can't resolve. I am in great despair. I am trying to integrate this code with another led library.**

**Comment by TannerHollis** [comment]
How are you implementing this into your code? I can help I just did this with C++ on RPI Zero W 1.0.

**Comment by Gadgetoid** [comment]
Closing as stale, and... uh... really, really vague.
