### ISSUE TITLE
rp_cm4_8gb_v1.1_support

### ISSUE THREAD

**Issue by S-Ashja** [jgarff/rpi_ws281x#511]
Need to add support for CM4  GB variant V1.1
`    {
        .hwver = 0xD03141, //CM4 8GB 32GB Wifi
        .type = RPI_HWVER_TYPE_PI4, //has a check on it cannot be changed
        .periph_base = PERIPH_BASE_RPI4,
        .videocore_base = VIDEOCORE_BASE_RPI2,
        .desc = "CM4 8GB 32GB Wifi"
    },`

**Comment by Gadgetoid** [comment]
It has been done!
