### ISSUE TITLE
Odroid C4 support

### ISSUE THREAD

**Issue by dieseltravis** [jgarff/rpi_ws281x#518]
I am running [Hyperion](https://github.com/hyperion-project) on a [Odroid C4](https://wiki.odroid.com/odroid-c4/odroid-c4) under Odroid's Ubuntu Mate install, however I get an error when using ws281x:
`2023-04-03T01:42:37.890Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: Hardware revision is not supported'`

Here is more info on the header pins:
https://wiki.odroid.com/odroid-c4/application_note/gpio/enhancement_gpio#tab__odroid-c4
![image](https://user-images.githubusercontent.com/17863/229579454-5a8546c7-bba7-4609-9bf2-47bc78290515.png)

**Comment by Gadgetoid** [comment]
This library does not and will not support Odroid boards, it's too closely coupled to the Pi hardware and reliant upon specific combinations of peripheral features.

**Comment by aleksas** [comment]
@dieseltravis  Made [Odroid c4 adaptation](https://github.com/hepingood/ws2812b/pull/24) of [hepingood/ws2812b](https://github.com/hepingood/ws2812b), hope that's helpful. Will try to improve timings as there are still some noticeable artifacts.
