### ISSUE TITLE
RPi 3B+ Rev 1.4: Hardware revision is not supported

### ISSUE THREAD

**Issue by dimzeta** [jgarff/rpi_ws281x#520]
```
$ grep -e Revision -e Model /proc/cpuinfo
Revision        : a020d4
Model           : Raspberry Pi 3 Model B Plus Rev 1.4
```

Everything works well on most of the Raspberry (3B+ & 4) but I have the famous `Hardware revision is not supported` error for this one.

Could you help me to resolve this?
Thanks! 😁

**Comment by Gadgetoid** [comment]
Should be fixed as of https://github.com/jgarff/rpi_ws281x/commit/c09fecb5ead9a33696f78913627c5693ca6a5c5a

Thanks!

(also in new 5.0.0 release of rpi_ws281x if you're using that)
