### ISSUE TITLE
Is it possible to use the additional SPI interfaces on the Raspberry Pi 4/CM4

### ISSUE THREAD

**Issue by hannescam** [jgarff/rpi_ws281x#546]
For my project I would need a way to control 5 separate LED strips using SPI with a Raspberry Pi 4 and later a CM4
And I would like to know if that would be possible
And would it be possible to use the spidev paths instead of the pin numbers

**Comment by jgarff** [comment]
Sorry, but no.  There are only 2 SPI controllers built into the chip.  These rely on special hardware in the chip and cannot be increased with software.
