### ISSUE TITLE
Servo Hat channel access

### ISSUE THREAD

**Issue by kelvien** [jgarff/rpi_ws281x#61]
I am just wondering if this library could access a servo hat's channels.
For example, the Adafruit 16-channel PWM/Servo hat (https://www.adafruit.com/product/2327)
I was thinking that since the hat provides 16 channels for PWM output, how do I get the library to access those channels to control my digital LED Light strip?

**Comment by jgarff** [comment]
Unfortunately no.  Those channels are not hardware PWM, but are instead software controlled PWM which is way too slow, and has too much jitter to support these types of LEDs.
