### ISSUE TITLE
Main.c hooks the wrong signal

### ISSUE THREAD

**Issue by rurwin** [jgarff/rpi_ws281x#64]
Sorry, not set up to do pull requests.

main.c:
instead of    sigaction(SIGKILL, &sa, NULL);
should be    sigaction(SIGINT, &sa, NULL);

There's no difference in behaviour just doing the fini, but I added code to turn all LEDs off, and that only works with this change. SIGINT is " Interrupt from keyboard", ie ctrl-c. SIGKILL is "Kill signal" and is the backstop when all else fails; "The signals SIGKILL and SIGSTOP cannot be caught, blocked, or ignored." See man 7 signal.

**Comment by jgarff** [comment]
Good catch.  Thanks.

**Comment by jgarff** [comment]
Fixed in commit 30a63e7b7028ecc17578bef927c6406606660f0e.

**Comment by jgarff** [comment]
Please also see commit 8d63a6c2fb870f11d20143a60bf7cff605cb0299.  I added the SIGTERM signal hook in case the user runs this program in the background and terminates with the kill command.

**Comment by rurwin** [comment]
Nice quick fix, thanks.
