### ISSUE TITLE
Does this library support RGB NeoPixels?

### ISSUE THREAD

**Issue by something15525** [jgarff/rpi_ws281x#65]
Specifically, I purchased these https://www.adafruit.com/products/1138 and I was wondering if these are supported, since I have a Raspberry Pi 1.

Thanks in advance!

**Comment by usefulthink** [comment]
Yes, they are supported. For wiring etc see the excellent guide here: https://learn.adafruit.com/neopixels-on-raspberry-pi/overview

**Comment by something15525** [comment]
Thank you!
