### ISSUE TITLE
Support for all PIs?

### ISSUE THREAD

**Issue by KuenzelIT** [jgarff/rpi_ws281x#67]
Hey,

does this library support all PIs from 0 to 3?

In any case, could you put this in the Readme somewhere? Thanks!

**Comment by jgarff** [comment]
Yes it does.  All Pis are supported.  I successfully tested it on a Pi3 as well a couple days ago.  Just make sure you have a recent kernel which includes the Broadcom videocore module.  Most distros work, raspian is what I typically use.  Thanks for the suggestion, I'll add this to the README.

**Comment by KuenzelIT** [comment]
Thank you!
