### ISSUE TITLE
Can I use this with 12v leds?

### ISSUE THREAD

**Issue by gavspav** [jgarff/rpi_ws281x#7]
I'm thinking the answer might be 'no' but I'm struggling to find any concrete information about this.
I have read that the signal voltage needs to be 70% of that powering the led's. Is that applicable for pwm voltage also?
I am a bit confused as to whether 12v ws2812 are actually driven at 12v or if the voltage is stepped down to 5v.
I'm thinking of trying it and seeing what happens but I thought I'd ask here because I don't like fried pi!

**Comment by Sciss** [comment]
@gavspav did you manage to get this working? I want to use 12V as well, unsure about the signal input, I guess it just works with 3.3 or 5V, and the 12V is simply for the LED power?
