### ISSUE TITLE
ODROID support

### ISSUE THREAD

**Issue by peel** [jgarff/rpi_ws281x#77]
Although I am no C dev, I was looking into running the library on ODROID C2. 
The pins are compatible, however there are some key differences. Starting with AArch64 architecture (coming to RPi3 sometime soon), HW naming scheme
```
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: ODROID-C2
Revision	: 020b
```
And kernel version
```
[root@hell4 python]# uname -r
3.14.29-16-ARCH
```
I quickly tried to fall back to running as RPi2, yet faced the issue of lacking RPI's VideoCore (/dev/vcio; as it sports Mali - /dev/mali ) and the /dev/mailbox  failed to be read (whereas creation worked fine). 

Also as I finally managed to compile on AArm64 by setting CFLAGS=-w, running ./test yeilds no results and exits momentarily, whereas running the python examples results in
```
[root@hell4 python]# python2 examples/strandtest.py
Traceback (most recent call last):
  File "examples/strandtest.py", line 8, in <module>
    from neopixel import *
  File "build/bdist.linux-aarch64/egg/neopixel.py", line 50, in <module>
  File "build/bdist.linux-aarch64/egg/neopixel.py", line 52, in Adafruit_NeoPixel
AttributeError: 'module' object has no attribute 'WS2811_STRIP_RGB'
``` 

Also simply replacing /dev/vcio to /dev/mali ends up with
```
ioctl_set_msg failed, errno 25: Inappropriate ioctl for device
```

Any ideas how can I follow with that?

Further reference: 
http://forum.odroid.com/viewtopic.php?f=117&t=8376
http://odroid.com/dokuwiki/doku.php?id=en:odroid-c2

**Comment by jgarff** [comment]
This library doesn't support the ODROID.  It only works on specific Broadcom processors present in the Raspberry Pi as it requires special hardware logic provided by the chip.  Unless there is a ODROID based around the exact same Broadcom parts used in the RPi, it won't work.

**Comment by guilhermegm** [comment]
@jgarff 

I'm using Ubuntu Mate 16 on rpi 3 and I got the same error on the lastest commit.

Thanks.

**Comment by puccaso** [comment]
im actually getting the same error on rpi3b with 64bit kernel/32bit userland

```
merateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4219:4237:1126/212758.099440:ERROR:sandbox_ipc_linux.cc(438)] /dev/vcio: ioctl: Inappropriate ioctl for device (25)
usrvcsm: [vcsm_malloc_cache]: [1] [mmal_vc_port buffer]: NULL size or invalid device!
usrvcsm: [vcsm_vc_hdl_from_hdl]: [1]: invalid device or handle!
usrvcsm: [vcsm_lock]: [1]: invalid device or invalid handle!
mmal: mmal_vc_shm_alloc: could not allocate 122880 bytes of shared memory (handle 0)
mmal: mmal_vc_port_payload_alloc: vc.ril.resize:out:0(bgra): failed to allocate 122880 bytes of shared memory
mmal: mmal_pool_initialise_buffer_headers: failed to allocate payload 0/16
[1:19:1126/212758.163385:ERROR:mmal_video_decoder.cc(1340)] ### mmal_port_pool_create failed: 16*122880
```
