### ISSUE TITLE
RPi3 issue

### ISSUE THREAD

**Issue by markab** [jgarff/rpi_ws281x#78]
Traceback (most recent call last):
  File "my.py", line 48, in <module>
    stick.begin()
  File "build/bdist.linux-armv7l/egg/neopixel.py", line 102, in begin
RuntimeError: ws2811_init failed with code -1

Getting this error on a raspi3 I guess the build is for a different processor?

**Comment by drewp** [comment]
Works for me on pi 3 model b 1.2. 

One easy way to see how far that init is getting is to log all the syscalls, like this:
# scons
# strace -f -s 500 ./test
...
open("/proc/cpuinfo", O_RDONLY)         = 3
fstat64(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fbe000
read(3, "processor\t: 0\nmodel name\t: ARMv7 Processor rev 4 (v7l)\nBogoMIPS\t: 38.40\nFeatures\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \nCPU implementer\t: 0x41\nCPU architecture: 7\nCPU variant\t: 0x0\nCPU part\t: 0xd03\nCPU revision\t: 4\n\nprocessor\t: 1\nmodel name\t: ARMv7 Processor rev 4 (v7l)\nBogoMIPS\t: 38.40\nFeatures\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \nCPU implementer\t: 0x41\nCPU architecture: 7\nCPU variant\t: 0x0"..., 1024) = 1024
read(3, "ariant\t: 0x0\nCPU part\t: 0xd03\nCPU revision\t: 4\n\nHardware\t: BCM2709\nRevision\t: a22082\nSerial\t\t: 000000008e399d01\n", 1024) = 112
close(3)                                = 0
munmap(0x76fbe000, 4096)                = 0
open("/dev/vcio", O_RDONLY)             = 3
ioctl(3, 0xc0046400, 0x7eaaa548)        = 0
ioctl(3, 0xc0046400, 0x7eaaa548)        = 0
open("/dev/mem", O_RDWR|O_SYNC)         = 4
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0x3d972000) = 0x76fbe000
close(4)                                = 0
open("/dev/mem", O_RDWR|O_SYNC)         = 4
mmap2(NULL, 36, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0x3f007000) = 0x76fbd000
close(4)                                = 0
open("/dev/mem", O_RDWR|O_SYNC)         = 4
mmap2(NULL, 40, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0x3f20c000) = 0x76fbc000
close(4)                                = 0
open("/dev/mem", O_RDWR|O_SYNC)         = 4
mmap2(NULL, 180, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0x3f200000) = 0x76fbb000
close(4)                                = 0
open("/dev/mem", O_RDWR|O_SYNC)         = 4
mmap2(NULL, 8, PROT_READ|PROT_WRITE, MAP_SHARED, 4, 0x3f101000) = 0x76fba000
close(4)                                = 0
nanosleep({0, 10000}, NULL)             = 0
nanosleep({0, 10000}, NULL)             = 0
...
