### ISSUE TITLE
RaspberryPi A+ revision not matched

### ISSUE THREAD

**Issue by macboy012** [jgarff/rpi_ws281x#79]
Using this library on a RaspberryPi A+, had issues with rpi_hw_detect() in rpihw.c. My rpi has a Revision of 0015 (21) but in the file the Model A+ is listed as having 0x12 (18) so there is no matched hardware and this function fails. All this manifests as: "ws2811_init failed with code -1"

If I can send any more device info let me know. My fix was to change the A+ revision in the file to one that matched my rpi's Revision.

**Comment by penfold42** [comment]
You just just add another paragraph of code with the new hardware ID.

Can you do this and create a pull request ?
