### ISSUE TITLE
ws2811_init failed with code -1 (NanoPi Board)

### ISSUE THREAD

**Issue by vinimendes3** [jgarff/rpi_ws281x#86]
We are in a project which we have to use Bluetooth and WiFi in the same board, therefore, we've opted to use a board called [NanoPi](http://nanopi.org/NanoPi_Feature.html).

On the board page, it seems that this board has GPIOs similars to Raspberry. 

I want to use this library to control neopixel but I'm getting the following error:

![13055513_974613705968424_4000721077945835938_n](https://cloud.githubusercontent.com/assets/3437722/14868269/202ad7a0-0ca3-11e6-888c-61c42f1635d5.jpg)

And reading issue #84 , it made me noticed that **rpihw.c** file is compatible for different boards but not for NanoPi. Is there any way to make this library compatible for [NanoPi](http://nanopi.org/NanoPi_Feature.html) ?

Thanks in advane,

**Comment by jgarff** [comment]
Unfortunately no.  This library supports _only_ Broadcom based hardware.
The NanoPi appears to use a incompatible Samsung part.
