### ISSUE TITLE
RPi Detection fails when warranty bit is set

### ISSUE THREAD

**Issue by andbey0nd** [jgarff/rpi_ws281x#97]
At line 274 of rpi_ws281x/**rpihw.c** a change is needed to detect properly "Revision" string for Raspberries with warranty bit set (i.e. after use of force_turbo or over_voltage settings).

`rev = strtoul(&substr[1], NULL, 16); // Base 16`

must be changed to:

`rev = (strtoul(&substr[1], NULL, 16) & 0xffffff; // Base 16`

For example my RPi2's original Revision was "0xa01041", but after using force_turbo (voiding the warranty) it became "0x**1**a01041" and later changed to "0x**3**a01041". The same thing happened on my RPi3, where the original revision was "0xa22082" and it became "0x**2**a22082".

I compiled hyperion with this change and now everything works as it should.

**Comment by jgarff** [comment]
Good to know, thanks.

**Comment by jgarff** [comment]
Fixed in aadcebabd5c122190d429b52e58e048850a7fb12 on the sk6812 branch.  Please re-test and let me know if you run into problems.  Thanks.
